// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: sms.proto

package sms

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VeriCodeClient is the client API for VeriCode service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VeriCodeClient interface {
	SendVeriCode(ctx context.Context, in *VeriCodeRequest, opts ...grpc.CallOption) (*VeriCodeReply, error)
}

type veriCodeClient struct {
	cc grpc.ClientConnInterface
}

func NewVeriCodeClient(cc grpc.ClientConnInterface) VeriCodeClient {
	return &veriCodeClient{cc}
}

func (c *veriCodeClient) SendVeriCode(ctx context.Context, in *VeriCodeRequest, opts ...grpc.CallOption) (*VeriCodeReply, error) {
	out := new(VeriCodeReply)
	err := c.cc.Invoke(ctx, "/sms.VeriCode/SendVeriCode", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VeriCodeServer is the server API for VeriCode service.
// All implementations must embed UnimplementedVeriCodeServer
// for forward compatibility
type VeriCodeServer interface {
	SendVeriCode(context.Context, *VeriCodeRequest) (*VeriCodeReply, error)
	mustEmbedUnimplementedVeriCodeServer()
}

// UnimplementedVeriCodeServer must be embedded to have forward compatible implementations.
type UnimplementedVeriCodeServer struct {
}

func (UnimplementedVeriCodeServer) SendVeriCode(context.Context, *VeriCodeRequest) (*VeriCodeReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendVeriCode not implemented")
}
func (UnimplementedVeriCodeServer) mustEmbedUnimplementedVeriCodeServer() {}

// UnsafeVeriCodeServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VeriCodeServer will
// result in compilation errors.
type UnsafeVeriCodeServer interface {
	mustEmbedUnimplementedVeriCodeServer()
}

func RegisterVeriCodeServer(s grpc.ServiceRegistrar, srv VeriCodeServer) {
	s.RegisterService(&VeriCode_ServiceDesc, srv)
}

func _VeriCode_SendVeriCode_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VeriCodeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VeriCodeServer).SendVeriCode(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/sms.VeriCode/SendVeriCode",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VeriCodeServer).SendVeriCode(ctx, req.(*VeriCodeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VeriCode_ServiceDesc is the grpc.ServiceDesc for VeriCode service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VeriCode_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sms.VeriCode",
	HandlerType: (*VeriCodeServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SendVeriCode",
			Handler:    _VeriCode_SendVeriCode_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "sms.proto",
}
