// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v3.12.4
// source: voxov.proto

package api

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// VOxOVClient is the client API for VOxOV service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type VOxOVClient interface {
	// gate session
	CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error)
	UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionReply, error)
	// auth authenticate
	Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateReply, error)
	WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIReply, error)
	// auth device
	CreateDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error)
	ReadDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error)
	UpdateDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error)
	DeleteDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error)
	ListDevice(ctx context.Context, in *ListDeviceRequest, opts ...grpc.CallOption) (*ListDeviceReply, error)
	AuthDevice(ctx context.Context, in *AuthDeviceRequest, opts ...grpc.CallOption) (*AuthDeviceReply, error)
	// person read
	ReadPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error)
}

type vOxOVClient struct {
	cc grpc.ClientConnInterface
}

func NewVOxOVClient(cc grpc.ClientConnInterface) VOxOVClient {
	return &vOxOVClient{cc}
}

func (c *vOxOVClient) CreateSession(ctx context.Context, in *CreateSessionRequest, opts ...grpc.CallOption) (*CreateSessionReply, error) {
	out := new(CreateSessionReply)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/CreateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) UpdateSession(ctx context.Context, in *UpdateSessionRequest, opts ...grpc.CallOption) (*UpdateSessionReply, error) {
	out := new(UpdateSessionReply)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/UpdateSession", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) Authenticate(ctx context.Context, in *AuthenticateRequest, opts ...grpc.CallOption) (*AuthenticateReply, error) {
	out := new(AuthenticateReply)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/Authenticate", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) WhoAmI(ctx context.Context, in *WhoAmIRequest, opts ...grpc.CallOption) (*WhoAmIReply, error) {
	out := new(WhoAmIReply)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/WhoAmI", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) CreateDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/CreateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) ReadDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/ReadDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) UpdateDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/UpdateDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) DeleteDevice(ctx context.Context, in *Device, opts ...grpc.CallOption) (*Device, error) {
	out := new(Device)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/DeleteDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) ListDevice(ctx context.Context, in *ListDeviceRequest, opts ...grpc.CallOption) (*ListDeviceReply, error) {
	out := new(ListDeviceReply)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/ListDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) AuthDevice(ctx context.Context, in *AuthDeviceRequest, opts ...grpc.CallOption) (*AuthDeviceReply, error) {
	out := new(AuthDeviceReply)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/AuthDevice", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vOxOVClient) ReadPerson(ctx context.Context, in *Person, opts ...grpc.CallOption) (*Person, error) {
	out := new(Person)
	err := c.cc.Invoke(ctx, "/voxov.VOxOV/ReadPerson", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VOxOVServer is the server API for VOxOV service.
// All implementations must embed UnimplementedVOxOVServer
// for forward compatibility
type VOxOVServer interface {
	// gate session
	CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error)
	UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionReply, error)
	// auth authenticate
	Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateReply, error)
	WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIReply, error)
	// auth device
	CreateDevice(context.Context, *Device) (*Device, error)
	ReadDevice(context.Context, *Device) (*Device, error)
	UpdateDevice(context.Context, *Device) (*Device, error)
	DeleteDevice(context.Context, *Device) (*Device, error)
	ListDevice(context.Context, *ListDeviceRequest) (*ListDeviceReply, error)
	AuthDevice(context.Context, *AuthDeviceRequest) (*AuthDeviceReply, error)
	// person read
	ReadPerson(context.Context, *Person) (*Person, error)
	mustEmbedUnimplementedVOxOVServer()
}

// UnimplementedVOxOVServer must be embedded to have forward compatible implementations.
type UnimplementedVOxOVServer struct {
}

func (UnimplementedVOxOVServer) CreateSession(context.Context, *CreateSessionRequest) (*CreateSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateSession not implemented")
}
func (UnimplementedVOxOVServer) UpdateSession(context.Context, *UpdateSessionRequest) (*UpdateSessionReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateSession not implemented")
}
func (UnimplementedVOxOVServer) Authenticate(context.Context, *AuthenticateRequest) (*AuthenticateReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Authenticate not implemented")
}
func (UnimplementedVOxOVServer) WhoAmI(context.Context, *WhoAmIRequest) (*WhoAmIReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method WhoAmI not implemented")
}
func (UnimplementedVOxOVServer) CreateDevice(context.Context, *Device) (*Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method CreateDevice not implemented")
}
func (UnimplementedVOxOVServer) ReadDevice(context.Context, *Device) (*Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadDevice not implemented")
}
func (UnimplementedVOxOVServer) UpdateDevice(context.Context, *Device) (*Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UpdateDevice not implemented")
}
func (UnimplementedVOxOVServer) DeleteDevice(context.Context, *Device) (*Device, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DeleteDevice not implemented")
}
func (UnimplementedVOxOVServer) ListDevice(context.Context, *ListDeviceRequest) (*ListDeviceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ListDevice not implemented")
}
func (UnimplementedVOxOVServer) AuthDevice(context.Context, *AuthDeviceRequest) (*AuthDeviceReply, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AuthDevice not implemented")
}
func (UnimplementedVOxOVServer) ReadPerson(context.Context, *Person) (*Person, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReadPerson not implemented")
}
func (UnimplementedVOxOVServer) mustEmbedUnimplementedVOxOVServer() {}

// UnsafeVOxOVServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VOxOVServer will
// result in compilation errors.
type UnsafeVOxOVServer interface {
	mustEmbedUnimplementedVOxOVServer()
}

func RegisterVOxOVServer(s grpc.ServiceRegistrar, srv VOxOVServer) {
	s.RegisterService(&VOxOV_ServiceDesc, srv)
}

func _VOxOV_CreateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).CreateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/CreateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).CreateSession(ctx, req.(*CreateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_UpdateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).UpdateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/UpdateSession",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).UpdateSession(ctx, req.(*UpdateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_Authenticate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthenticateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).Authenticate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/Authenticate",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).Authenticate(ctx, req.(*AuthenticateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_WhoAmI_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(WhoAmIRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).WhoAmI(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/WhoAmI",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).WhoAmI(ctx, req.(*WhoAmIRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_CreateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).CreateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/CreateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).CreateDevice(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_ReadDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).ReadDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/ReadDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).ReadDevice(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_UpdateDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).UpdateDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/UpdateDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).UpdateDevice(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_DeleteDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Device)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).DeleteDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/DeleteDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).DeleteDevice(ctx, req.(*Device))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_ListDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).ListDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/ListDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).ListDevice(ctx, req.(*ListDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_AuthDevice_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AuthDeviceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).AuthDevice(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/AuthDevice",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).AuthDevice(ctx, req.(*AuthDeviceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VOxOV_ReadPerson_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Person)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VOxOVServer).ReadPerson(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/voxov.VOxOV/ReadPerson",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VOxOVServer).ReadPerson(ctx, req.(*Person))
	}
	return interceptor(ctx, in, info, handler)
}

// VOxOV_ServiceDesc is the grpc.ServiceDesc for VOxOV service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VOxOV_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "voxov.VOxOV",
	HandlerType: (*VOxOVServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateSession",
			Handler:    _VOxOV_CreateSession_Handler,
		},
		{
			MethodName: "UpdateSession",
			Handler:    _VOxOV_UpdateSession_Handler,
		},
		{
			MethodName: "Authenticate",
			Handler:    _VOxOV_Authenticate_Handler,
		},
		{
			MethodName: "WhoAmI",
			Handler:    _VOxOV_WhoAmI_Handler,
		},
		{
			MethodName: "CreateDevice",
			Handler:    _VOxOV_CreateDevice_Handler,
		},
		{
			MethodName: "ReadDevice",
			Handler:    _VOxOV_ReadDevice_Handler,
		},
		{
			MethodName: "UpdateDevice",
			Handler:    _VOxOV_UpdateDevice_Handler,
		},
		{
			MethodName: "DeleteDevice",
			Handler:    _VOxOV_DeleteDevice_Handler,
		},
		{
			MethodName: "ListDevice",
			Handler:    _VOxOV_ListDevice_Handler,
		},
		{
			MethodName: "AuthDevice",
			Handler:    _VOxOV_AuthDevice_Handler,
		},
		{
			MethodName: "ReadPerson",
			Handler:    _VOxOV_ReadPerson_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "voxov.proto",
}
